version: "3.7"

services:
  localstack:
    container_name: interview-recorder.localstack
    image: localstack/localstack
    environment:
      - API_NAME=interview-audio-to-s3
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PYTHONUNBUFFERED=1
      - SERVICES=lambda,s3
      - S3_BUCKET_NAME=interview-responses
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=lambda,apigateway,s3
    ports:
      - "45660:4566"
      - "8080:8080"
    expose:
      - "4566"
    volumes:
      - "./containers/localstack/data:/tmp/localstack"
      - "./bin/localstack:/docker-entrypoint-initaws.d"
      - "./lambda/dist:/tmp/zip"